config/routes.rb
Rails.application.routes.draw do
  resources :scenarios do
    member do
      get :translate
      get :locations
      get :export
    end
    collection do
      get 'build/:date', action: :build
    end
  end

  resources :lines, only: [:update] do
    member do
      post :who
    end
  end

  resources :locations, only: [:update]

  devise_for :users

  root to: 'scenarios#index'
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :fragment
  belongs_to :user, foreign_key: :updated_by, required: false

  after_update :recalc_translated

  # Name or email of person who updated
  def updated_by_person
    return '' if updated_by.nil?
    user.username || user.email
  end

  # Is who may be translated
  def who_translatable?
    !(who.nil? || who.blank? || ['?', '%'].include?(who[0]))
  end

  # Returns either translated or original talker
  def new_who
    who_translatable? && who_translated.present? ? transcode(who_translated) : who
  end

  # Returns either translated or original text
  def new_content
    content_translated.present? ? transcode(content_translated) : content
  end

  # Change translation of Who for all lines of the scenario
  def change_all_who(translated_value)
    Line.where(fragment: fragment.scenario.fragments, who: who)
        .update_all(who_translated: translated_value)
  end

  # Transcode string
  def transcode(s)
    s.split('').reduce("") { |a, c| a + (trans_table[c].nil? ? c : trans_table[c]) }
  end

  # Returns transcoding table
  def trans_table
    @trans_table ||= File.readlines(Rails.root.join("data", "transcode.txt"))
                         .collect { |e| e.strip.split(' ') }.to_h
  end

  private

    def recalc_translated
      scenario = fragment.scenario
      scenario.update! translated: Line.where(fragment: scenario.fragments)
                                       .where.not(content_translated: nil).count
    end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :who]

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params.merge(updated_by: current_user.id))
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # Change translation of Who to all lines of this scenario
  def who
    @line.change_all_who params[:trans_val]
    render json: {}, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:fragment_id, :who, :content, :who_translated, :content_translated, :updated_by)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_with(model: line, local: true) do |form| %>
  <% if line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fragment_id %>
    <%= form.text_field :fragment_id %>
  </div>

  <div class="field">
    <%= form.label :who %>
    <%= form.text_field :who %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :who_translated %>
    <%= form.text_field :who_translated %>
  </div>

  <div class="field">
    <%= form.label :content_translated %>
    <%= form.text_field :content_translated %>
  </div>

  <div class="field">
    <%= form.label :updated_by %>
    <%= form.number_field :updated_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lines</h1>

<table>
  <thead>
    <tr>
      <th>Fragment</th>
      <th>Who</th>
      <th>Content</th>
      <th>Who translated</th>
      <th>Content translated</th>
      <th>Updated by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.fragment %></td>
        <td><%= line.who %></td>
        <td><%= line.content %></td>
        <td><%= line.who_translated %></td>
        <td><%= line.content_translated %></td>
        <td><%= line.updated_by %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fragment:</strong>
  <%= @line.fragment %>
</p>

<p>
  <strong>Who:</strong>
  <%= @line.who %>
</p>

<p>
  <strong>Content:</strong>
  <%= @line.content %>
</p>

<p>
  <strong>Who translated:</strong>
  <%= @line.who_translated %>
</p>

<p>
  <strong>Content translated:</strong>
  <%= @line.content_translated %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @line.updated_by %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>