config/routes.rb
Rails.application.routes.draw do
  resources :scenarios do
    member do
      get :translate
      get :locations
      get :export
    end
    collection do
      get 'build/:date', action: :build
    end
  end

  resources :lines, only: [:update] do
    member do
      post :who
    end
  end

  resources :locations, only: [:update]

  devise_for :users

  root to: 'scenarios#index'
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  has_many :fragments

  # Import from the binary file
  def import
    fragments.each(&:destroy)
    File.open(bin_file_name, "rb") do |f|
      order = 0
      new_lines = 0
      until f.eof?
        new_lines += import_next_object(f, order)
        order += 1
      end
      update! lines: new_lines
    end
    add_locations
  end

  # Additionally import locations
  def add_locations
    new_locations = 0
    fragments.each do |f|
      next unless f.location?
      new_locations += add_location f
    end
    update! locations_count: Location.where(fragment: fragments).count
  end

  # Export to the binary file
  def export
    return if fragments.count.zero?
    File.open("#{bin_file_name}.new", "wb") do |f|
      i = 0;
      fragments.order(:order).each do |fr|
        i = export_object f, fr, i
      end
    end
  end

  # Completion color
  def completion_color
    return "ffffff" if translated.nil? || translated.zero? || lines.nil? || lines.zero?
    return "ff7777" if translated > lines
    return "#{ (255 - 128 * translated / lines).to_s(16) }ff77"
  end

  # Binary file name
  def bin_file_name(ext = 'in')
    Rails.root.join('data', "#{filename}.#{ext}")
  end

  # Import an object from the file
  def import_next_object(f, order)
    f_size = read_word(f)
    f_type = read_word(f)
    f_data = f.read(f_size - 4)
    frag = Fragment.create! order: order, orig_data: f_data, scenario_id: id, f_type: f_type, size: f_size
    f_type == 16 ? create_line(frag) : 0
  end

  # Create text fragment if text or person object is imported
  def create_line(frag)
    who = fragments.find_by order: frag.order - 1, f_type: 24
    Line.create! fragment_id: frag.id, who: (who.nil? ? nil : who.orig_text), content: frag.orig_text
    1
  end

  # Add a location for a fragment
  def add_location(f)
    return 0 if !f.location? || Location.exists?(fragment: f)
    Location.create! fragment_id: f.id, content: f.orig_text
    1
  end

  # Export next object to the file
  def export_object(f, fr, i)
    f.write pack_dword(fr.calc_size)
    f.write pack_dword(fr.f_type)
    if fr.translatable?
      # f.write pack_dword(fr.calc_size)
      # f.write pack_dword(fr.f_type)
      f.write fr.orig_data[0..3]
      f.write fr.translated_text
      i += 1
    else
      # f.write pack_dword(fr.size)
      # f.write pack_dword(fr.f_type)
      f.write fr.orig_data
    end
    i
  end

  # Read a word from the file
  def read_word(f)
    w = f.read(2).bytes
    (w[1] << 8) + w[0]
  end

  # Pack double word for export
  def pack_dword(w)
    [w & 255, w >> 8].pack("c*")
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :user_is_admin, only: [:new, :edit, :update, :destroy, :import]
  before_action :set_scenario, only: [:show, :edit, :update, :destroy, :translate, :locations, :import, :export]

  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = Scenario.all
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: 'Scenario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Shows transtation page
  def translate
    @lines = Line.where(fragment: @scenario.fragments).order(:id).page params[:page]
  end

  # Shows locations transtation page
  def locations
    @locations = Location.where(fragment: @scenario.fragments).order(:id).page params[:page]
  end

  # Import from the binary file
  def import
    @scenario.import
    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: 'Scenario was successfully imported.' }
      format.json { head :no_content }
    end
  end

  # Export to the binary file
  def export
    @scenario.export
    send_file "#{@scenario.bin_file_name}.new", type: 'application/octet-stream'
  end

  # Allows to download a specific game build
  def build
    date = params[:date][/\d{8}/] or not_found
    filename = "7scarlet-rus-build#{date}.zip"
    full_path = Rails.root.join 'data', filename
    send_file full_path, type: 'application/zip', filename: filename
    headers['Content-Length'] = File.size full_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scenario_params
      params.require(:scenario).permit(:name, :filename, :lines, :translated)
    end

    # Checks id the user is admin
    def user_is_admin
      unless current_user.admin?
      flash[:notice] = "You may only view existing scenarios."
      redirect_to root_path
      end
    end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_with(model: scenario, local: true) do |form| %>
  <% if scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
      <% scenario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :filename %>
    <%= form.text_field :filename %>
  </div>

  <div class="field">
    <%= form.label :lines %>
    <%= form.number_field :lines %>
  </div>

  <div class="field">
    <%= form.label :translated %>
    <%= form.number_field :translated %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<h1>Editing Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenarios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Filename</th>
      <th>Lines</th>
      <th>Translated</th>
      <th>Locations</th>
      <th>Translated</th>
      <th<%= current_user.admin? ? ' colspan="4"' : '' %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr style="background-color:#<%= scenario.completion_color %>">
        <td><%= scenario.name %></td>
        <td><%= scenario.filename %></td>
        <td><%= scenario.lines %></td>
        <td><%= scenario.translated.to_i %> (<%= 100 * scenario.translated.to_i / scenario.lines.to_i %>%)</td>
        <td><%= scenario.locations_count %></td>
        <td><%= scenario.locations_translated.to_i %> (<%= 100 * scenario.locations_translated.to_i / (scenario.locations_count.to_i.zero? ? 1 : scenario.locations_count.to_i) %>%)</td>
        <% if current_user.admin? %>
          <td><%= link_to 'Show', scenario %></td>
          <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
          <td><%= link_to 'Destroy', scenario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'Translate', translate_scenario_path(scenario) %></td>
        <td><%= link_to 'Locations', locations_scenario_path(scenario) %></td>
        <td><%= link_to 'Export', export_scenario_path(scenario) %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr style="font-weight: bold;">
      <td>All scenarios</td>
      <td></td>
      <td><%= @scenarios.sum(&:lines) %></td>
      <td><%= @scenarios.sum { |s| s.translated.to_i } %> (<%= 100 * @scenarios.sum { |s| s.translated.to_i } / @scenarios.sum(&:lines) %>%)</td>
      <td><%= @scenarios.sum(&:locations_count) %></td>
      <td><%= @scenarios.sum { |s| s.locations_translated.to_i } %> (<%= 100 * @scenarios.sum { |s| s.locations_translated.to_i } / (@scenarios.sum(&:locations_count).zero? ? 1 : @scenarios.sum(&:locations_count)) %>%)</td>
      <td<%= current_user.admin? ? ' colspan="4"' : '' %></td>
      <td></td>
      <td></td>
    </tr>
  </tfoot>
</table>

<br>

<% if current_user.admin? %>
  <%= link_to 'New Scenario', new_scenario_path %>
<% end %>

app/views/scenarios/locations.html.erb
<h1>Translate locations for <%= @scenario.name %></h1>

<%= paginate @locations %>
<table>
  <thead>
    <tr>
      <th width="45%">Text</th>
      <th width="45%">Translated text</th>
      <th width="8%">Last update</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.content %></td>
        <td><input type="text" id="txt<%= location.id %>" size=30 maxlength="63" value="<%= location.content_translated.to_s.tr('"', '\"') %>"></td>
        <td id="upd<%= location.id %>">
          <% unless location.updated_by.nil? %>
            <%= location.updated_at.iso8601[0..9] %> by <%= location.updated_by_person %>
          <% end %>
        </td>
        <td><button onclick="save_location(<%= location.id %>)">Save</button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @locations %>

<br>

app/views/scenarios/new.html.erb
<h1>New Scenario</h1>

<%= render 'form', scenario: @scenario %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scenario.name %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @scenario.filename %>
</p>

<p>
  <strong>Lines:</strong>
  <%= @scenario.lines %>
</p>

<p>
  <strong>Translated:</strong>
  <%= @scenario.translated %>
</p>

<%= link_to 'Edit', edit_scenario_path(@scenario) %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/translate.html.erb
<h1>Translate fragments for <%= @scenario.name %></h1>

<%= paginate @lines %>
<table>
  <thead>
    <tr>
      <th>Person</th>
      <th width="38%">Text</th>
      <th>Translated person</th>
      <th></th>
      <th width="38%">Translated text</th>
      <th width="8%">Last update</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td id="who<%= line.id %>"><%= line.who %></td>
        <td><%= line.content.tr("\n", "<br>") %></td>
        <td>
          <% if line.who_translatable? %>
            <input id="twho<%= line.id %>" type="text" size="12" value="<%= line.who_translated.to_s.tr('"', '\"') %>">
          <% else %>
            <%= line.who %>
          <% end %>
        </td>
        <td>
          <% if line.who_translatable? %>
            <button onclick="change_who(<%= line.id %>)">Change all</button>
          <% end %>
        </td>
        <td><textarea class="transarea" id="txt<%= line.id %>"><%= line.content_translated.to_s.tr('"', '\"') %></textarea></td>
        <td id="upd<%= line.id %>">
          <% unless line.updated_by.nil? %>
            <%= line.updated_at.iso8601[0..9] %> by <%= line.updated_by_person %>
          <% end %>
        </td>
        <td><button onclick="save_line(<%= line.id %>)">Save</button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @lines %>

<br>